[project]
name = "03-knowledge-graphs-for-rag"
version = "0.1.0"
description = "Learning Knowledge Graphs for RAG"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-community>=0.4.1",
    "neo4j>=6.1.0",
]
