[project]
name = "02-vector-databases-from-embeddings-to-applications"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "networkx>=3.5",
    "numpy>=2.3.5",
    "utils>=1.0.2",
]
